// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenMultiplePDFDialog() {
  return window['go']['main']['App']['OpenMultiplePDFDialog']();
}

export function OpenPDFDialog() {
  return window['go']['main']['App']['OpenPDFDialog']();
}

export function ProcessMultiplePDFs(arg1) {
  return window['go']['main']['App']['ProcessMultiplePDFs'](arg1);
}

export function ProcessPDF(arg1) {
  return window['go']['main']['App']['ProcessPDF'](arg1);
}
