// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenMultiplePDFDialog():Promise<Array<string>>;

export function OpenPDFDialog():Promise<string>;

export function ProcessMultiplePDFs(arg1:Array<string>):Promise<Array<string>|Array<Error>>;

export function ProcessPDF(arg1:string):Promise<string>;
