// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenPDFDialog():Promise<string>;

export function ProcessPDF(arg1:string):Promise<string>;
